### ISSUE TITLE
Hello，I would like to reproduce your work

### ISSUE THREAD

**Issue by daidaidaluannan** [rsinghlab/MADDi#1]
It is a great honor for me to read your article on Multimodal Attention-based Deep Learning for Alzheimer’s Disease Diagnosis. Your clear and compacted declaration inspired me a lot. However, in **notebook general/diagnosis_making.ipynb** `new = pd.DataFrame.from_dict(d, orient='index').reset_index()` ，'d' does not seem to be defined. Meanwhile, I'd like to know where the file **all_img_try1_10_31_2021.csv** came from, I didn't find it in the ADNI database. 

Thanks!

**Comment by michalg04** [comment]
Thank you for reaching out @daidaidaluannan! I apologize for missing the "d" variable, I have corrected the code to include where the variable came from. As far as the file - it is the metadata file that one can get from downloading MRI images from ADNI. It is not a standard CSV available on ADNI, but rather something that is specific to the exact MRI scans you chose to download. Once you download images, you can also download the metadata associated with those specific images. Hope that helps!
