### ISSUE TITLE
Genetic data processing

### ISSUE THREAD

**Issue by Camelus-to** [rsinghlab/MADDi#11]
Hello author, I am working with genetic data, filter_vcfs.py,
start = vcf_file.find("ADNI_ID.") + len("ADNI_ID.")
end = vcf_file.find("output.vcf")
For the genetic data in ANDI dataset, do you use.plink files for genetic data processing or.vCF files? I can't find the string ADNI_ID. Did you name these by yourself? Thank you for your answer

**Comment by shuilinggirl** [comment]
> 你好，作者，我正在处理遗传数据，filter_vcfs.py，
> start = vcf_file.find("ADNI_ID.") + len("ADNI_ID.")
> end = vcf_file.find("output.vcf")
> 对于ANDI数据集中的遗传数据，您是否使用.plink文件进行遗传数据处理或.vCF文件？我找不到字符串ADNI_ID。这些是你自己命名的吗？谢谢你的回答

hello, May I ask if your problem has been resolved? I would like to discuss some issues with you

**Comment by michalg04** [comment]
Hi there! Sorry for the delayed response. We use vCF files as the variable vcf_file suggests. It seems that ADNI might have updated some of their files throughout the years (this was done in early 2021), so ADNI_ID might be named something different. Either way, it's the identifier of the patient, so you just need to look for that in whatever file you have.

**Comment by michalg04** [comment]
Hi there! Sorry for the delayed response. We use vCF files as the variable vcf_file suggests. It seems that ADNI might have updated some of their files throughout the years (this was done in early 2021), so ADNI_ID might be named something different. Either way, it's the identifier of the patient, so you just need to look for that in whatever file you have.

**Comment by michalg04** [comment]
Hi there! Sorry for the delayed response. We use vCF files as the variable vcf_file suggests. It seems that ADNI might have updated some of their files throughout the years (this was done in early 2021), so ADNI_ID might be named something different. Either way, it's the identifier of the patient, so you just need to look for that in whatever file you have.
