### ISSUE TITLE
Request to share preprocessed data

### ISSUE THREAD

**Issue by lyzy-cai-czh** [rsinghlab/MADDi#13]
Dear：
Thank you for sharing your code openly; I've learned a lot from your article. However, due to data versioning issues, many of us have encountered significant obstacles when trying to replicate the experiments. The original data is protected for privacy reasons and cannot be shared publicly. Could I kindly request that you provide all preprocessed data for me to train the models? If possible, I would greatly appreciate it.
My email: lyzyczh@gamil.com

**Comment by sydat2701** [comment]
> Dear： Thank you for sharing your code openly; I've learned a lot from your article. However, due to data versioning issues, many of us have encountered significant obstacles when trying to replicate the experiments. The original data is protected for privacy reasons and cannot be shared publicly. Could I kindly request that you provide all preprocessed data for me to train the models? If possible, I would greatly appreciate it. My email: [lyzyczh@gamil.com](mailto:lyzyczh@gamil.com)

Hi, I'm facing the same problem with you.  Did you solve it? If yes, could you share it with me, because I also really want to experience with this work. Thank you so much for your help.
