### ISSUE TITLE
run filter_vcfs.py error

### ISSUE THREAD

**Issue by zhouqixiang35** [rsinghlab/MADDi#15]
When I run filter_ vcfs.py，error:Error -3 while decompressing data: invalid distance too far back appears. How can this be resolved? The data is downloaded from ADNI using ADNI WGs Data - GATK SNV+Index call chr1 of 23, and then decompressed using the tar command to enter the filter_ vcfs.py.

**Comment by michalg04** [comment]
Hi there! Thanks for reading our paper. We followed the downloading steps from this paper: https://www.nature.com/articles/s41598-020-74399-w located in their appendix. I have not seen this error before, so I am not sure if this has to do with how you downloaded or with version incompatibility.
