### ISSUE TITLE
doubt regarding the dataset

### ISSUE THREAD

**Issue by Atith-Gandhi** [rsinghlab/MADDi#2]
Hi Michal! We are a group of students from Georgia Tech working on Alzheimer Disease Detection. We came across your paper  MADDi and are planning on implementing it. We have gained access to the ADNI dataset but we are unable to find the MRI images folder used in your source code preprocess_images.py and the metadata (all_img_try1_10_31_2021.csv) associated with it. Can you point us where to find it? We would be extremely grateful if you can help us with this.

**Comment by michalg04** [comment]
Hi Atith! Thanks for reading my paper, I appreciate it! There is a comment above the line reading all_img_try1_10_31_2021.csv which is as follows: "#this file is the metadata file that one can get from downloading MRI images from ADNI". Meaning, this specific file name does not exist as part of ADNI - rather, when you download the images from the ADNI website, you will _automatically_ get a metadata file that will be specific to the exact images you selected. I used the filtering tools that are part of the ADNI imaging framework to filter for the MRI scans that I wanted (the type and studies mentioned in the paper), and that generated a csv file as well as all the image files. I named it "all_img_try..." as a way to keep track of my downloading attempts, and have now changed it in the code to be less confusing. Hope that made sense!
