### ISSUE TITLE
Doubt regarding dataset

### ISSUE THREAD

**Issue by ManojKumar002** [rsinghlab/MADDi#5]
Hello,
I have been working on your paper and came across the file  "preprocess_genetic/concat_vcfs.py" where we require "DIAGNOSIS_TABLE" dataset, which is mentioned in the 12th line of that file. Can you please share the details regarding the dataset,If possible share the steps to obtain that dataset.

**Comment by michalg04** [comment]
Hi there,
If I understand your question correctly, you should first create the diagnosis table by following the in general/diagnosis_making.ipynb. The files there can be found in the ADNI file system. Hope this helps!
