### ISSUE TITLE
Need clarification in code

### ISSUE THREAD

**Issue by ManojKumar002** [rsinghlab/MADDi#9]
In the file "preprocess_genetic/concat_vcfs.py" on 25th line you have created a variable named "merged" and done many operation on that, finally to produce a pickle file on 37th line.But you haven't used that file anywhere in other part of the project.
Can you please give clarification on the usage of that file?

**Comment by michalg04** [comment]
Hi there! Thank you for reaching out. At the end of concat_vcfs.py I create a pickle file named "all_vcfs.pkl", which is the first file being read in preprocess_genetic/create_genetic_dataset.ipynb. Hope that helps!
